(function (spaceCore) {
  "use strict";

  const COLUMNS = 27;
  const ROWS = 21;

  spaceCore.config = {
    COLUMNS,
    ROWS,
    CORE_X: Math.floor(COLUMNS / 2),
    CORE_Y: Math.floor(ROWS / 2),
    DIRECTIONS: ["up", "right", "down", "left"],
    INITIAL_SCRAP: 260,
    INITIAL_INVENTORY: {
      "ship-scaffold": 28,
      "power-generator": 2,
      engine: 4,
      laser: 2,
      "shield-block": 1,
      cannon: 1,
      "ammo-factory": 1,
      "repair-bot-block": 1,
      "salvage-collector": 1,
      "conveyor-belt": 12,
      "splitter-conveyor": 3,
      "electric-cable": 24,
    },
    RESEARCH_PROJECTS: [
      {
        id: "targeting-computer",
        name: "Targeting Computer",
        section: "weapons",
        tier: 0,
        lane: 1,
        scrap: 65,
        parts: { laser: 1, "electric-cable": 2 },
        description: "Installs basic prediction hardware for weapon mounts.",
        effect: "Player weapons gain 10% range.",
      },
      {
        id: "laser-capacitors",
        name: "Laser Capacitors",
        section: "weapons",
        tier: 1,
        lane: 0,
        requires: ["targeting-computer"],
        scrap: 115,
        parts: { laser: 1, "power-generator": 1, "electric-cable": 3 },
        description: "Stores cleaner bursts of power beside laser emitters.",
        effect: "Laser-class weapons deal 10% more damage.",
      },
      {
        id: "projectile-ballistics",
        name: "Projectile Ballistics",
        section: "weapons",
        tier: 1,
        lane: 2,
        requires: ["targeting-computer"],
        scrap: 120,
        parts: { cannon: 1, "electric-cable": 3 },
        description: "Adds simple firing tables and better cannon stabilizers.",
        effect: "Cannon-class weapons deal 12% more damage and fire 8% faster shells.",
      },
      {
        id: "beam-laser",
        name: "Beam Laser",
        section: "weapons",
        tier: 2,
        lane: 0,
        requires: ["laser-capacitors"],
        unlocks: "beam-laser",
        scrap: 170,
        parts: { laser: 2, "power-generator": 1 },
        description: "Unlocks a longer-range laser with a heavier beam assembly.",
        effect: "Unlocks the Beam Laser ship part.",
      },
      {
        id: "focused-optics",
        name: "Focused Optics",
        section: "weapons",
        tier: 3,
        lane: 0,
        requires: ["beam-laser"],
        scrap: 245,
        parts: { laser: 2, "power-generator": 1, "electric-cable": 6 },
        description: "Polishes beam lenses and adds micro-adjusters to laser housings.",
        effect: "Laser-class weapons gain another 8% range.",
      },
      {
        id: "pulse-laser",
        name: "Pulse Laser",
        section: "weapons",
        tier: 2,
        lane: 1,
        requires: ["laser-capacitors"],
        unlocks: "pulse-laser",
        scrap: 220,
        parts: { laser: 3, "electric-cable": 6 },
        description: "Unlocks a rapid-fire laser optimized for close combat.",
        effect: "Unlocks the Pulse Laser ship part.",
      },
      {
        id: "burst-cyclers",
        name: "Burst Cyclers",
        section: "weapons",
        tier: 3,
        lane: 1,
        requires: ["pulse-laser"],
        scrap: 260,
        parts: { laser: 2, "conveyor-belt": 4, "electric-cable": 6 },
        description: "Adds synchronized charge cycling for weapons that fire in short bursts.",
        effect: "Laser-class weapons reload 8% faster.",
      },
      {
        id: "long-range-cannon",
        name: "Long Cannon",
        section: "weapons",
        tier: 2,
        lane: 2,
        requires: ["projectile-ballistics"],
        unlocks: "long-range-cannon",
        scrap: 190,
        parts: { cannon: 2, "electric-cable": 4 },
        description: "Unlocks an extended cannon barrel for long-distance shell fire.",
        effect: "Unlocks the Long Cannon ship part.",
      },
      {
        id: "magnetic-loaders",
        name: "Magnetic Loaders",
        section: "weapons",
        tier: 3,
        lane: 2,
        requires: ["long-range-cannon"],
        scrap: 230,
        parts: { cannon: 2, "conveyor-belt": 4, "electric-cable": 4 },
        description: "Uses magnetic feed rails to seat cannon shells faster.",
        effect: "Cannon-class weapons reload 12% faster.",
      },
      {
        id: "railgun",
        name: "Railgun",
        section: "weapons",
        tier: 4,
        lane: 2,
        requires: ["magnetic-loaders"],
        unlocks: "railgun",
        scrap: 340,
        parts: { cannon: 3, "power-generator": 2, "electric-cable": 6 },
        description: "Unlocks an extreme-range magnetic slug launcher.",
        effect: "Unlocks the Railgun ship part.",
      },
      {
        id: "kinetic-penetrators",
        name: "Kinetic Penetrators",
        section: "weapons",
        tier: 5,
        lane: 2,
        requires: ["railgun"],
        scrap: 430,
        parts: { cannon: 4, "power-generator": 2, "electric-cable": 8 },
        description: "Shapes cannon and railgun rounds around dense penetrator cores.",
        effect: "Cannon-class weapons deal another 10% damage.",
      },
      {
        id: "gimbal-mounts",
        name: "Gimbal Mounts",
        section: "mobility",
        tier: 0,
        lane: 1,
        scrap: 70,
        parts: { engine: 1, "conveyor-belt": 2 },
        description: "Rebuilds engine brackets so thrust transfers more cleanly.",
        effect: "Player engines produce 8% more thrust.",
      },
      {
        id: "thrust-vectoring",
        name: "Thrust Vectoring",
        section: "mobility",
        tier: 1,
        lane: 1,
        requires: ["gimbal-mounts"],
        scrap: 115,
        parts: { engine: 1, "electric-cable": 4 },
        description: "Adds movable exhaust vanes for better rotational control.",
        effect: "Player engines produce another 8% more thrust.",
      },
      {
        id: "overdrive-engine",
        name: "Overdrive Engine",
        section: "mobility",
        tier: 2,
        lane: 0,
        requires: ["thrust-vectoring"],
        unlocks: "overdrive-engine",
        scrap: 150,
        parts: { engine: 2, "conveyor-belt": 3 },
        description: "Unlocks a stronger engine for faster ships.",
        effect: "Unlocks the Overdrive Engine ship part.",
      },
      {
        id: "inertial-dampers",
        name: "Inertial Dampers",
        section: "mobility",
        tier: 2,
        lane: 2,
        requires: ["thrust-vectoring"],
        scrap: 150,
        parts: { engine: 1, "power-generator": 1, "electric-cable": 4 },
        description: "Adds motion compensation hardware to bleed off unwanted drift.",
        effect: "Player ships settle unwanted drift and rotation faster.",
      },
      {
        id: "mass-balancing",
        name: "Mass Balancing",
        section: "mobility",
        tier: 3,
        lane: 2,
        requires: ["inertial-dampers"],
        scrap: 205,
        parts: { "ship-scaffold": 8, engine: 1, "electric-cable": 5 },
        description: "Moves heavy systems closer to the thrust axis and balances the hull.",
        effect: "Player ships drift even less after thrusting.",
      },
      {
        id: "injector-tuning",
        name: "Injector Tuning",
        section: "mobility",
        tier: 3,
        lane: 0,
        requires: ["overdrive-engine"],
        scrap: 210,
        parts: { engine: 2, "power-generator": 1, "conveyor-belt": 4 },
        description: "Improves fuel timing in advanced thruster assemblies.",
        effect: "Player engines produce another 10% more thrust.",
      },
      {
        id: "quantum-thruster",
        name: "Quantum Thruster",
        section: "mobility",
        tier: 4,
        lane: 0,
        requires: ["injector-tuning"],
        unlocks: "quantum-thruster",
        scrap: 320,
        parts: { engine: 3, "power-generator": 1, "conveyor-belt": 4 },
        description: "Unlocks an endgame thruster with extreme output.",
        effect: "Unlocks the Quantum Thruster ship part.",
      },
      {
        id: "micro-jump-plating",
        name: "Micro-Jump Plating",
        section: "mobility",
        tier: 5,
        lane: 0,
        requires: ["quantum-thruster", "mass-balancing"],
        scrap: 410,
        parts: { engine: 4, "power-generator": 2, "ship-scaffold": 8 },
        description: "Reinforces the hull around extreme thrusters so acceleration stays controllable.",
        effect: "Player engines gain a final 8% thrust boost.",
      },
      {
        id: "insulated-conduits",
        name: "Insulated Conduits",
        section: "power",
        tier: 0,
        lane: 1,
        scrap: 60,
        parts: { "electric-cable": 6, "ship-scaffold": 3 },
        description: "Replaces bare cable runs with cleaner insulated channels.",
        effect: "Prepares the ship for higher-output generator upgrades.",
      },
      {
        id: "generator-coils",
        name: "Generator Coils",
        section: "power",
        tier: 1,
        lane: 0,
        requires: ["insulated-conduits"],
        scrap: 125,
        parts: { "power-generator": 1, "electric-cable": 5 },
        description: "Rewinds generator coils to draw more power from each unit.",
        effect: "Each Power Generator and Fusion Generator produce 1 additional power.",
      },
      {
        id: "high-capacity-bus",
        name: "High-Capacity Bus",
        section: "power",
        tier: 1,
        lane: 2,
        requires: ["insulated-conduits"],
        scrap: 120,
        parts: { "electric-cable": 10, "conveyor-belt": 2 },
        description: "Adds thicker shared power rails through the hull.",
        effect: "Prepares the grid for fusion and capacitor upgrades.",
      },
      {
        id: "fusion-generator",
        name: "Fusion Generator",
        section: "power",
        tier: 2,
        lane: 0,
        requires: ["generator-coils"],
        unlocks: "fusion-generator",
        scrap: 270,
        parts: { "power-generator": 2, "electric-cable": 8 },
        description: "Unlocks a stronger generator built around a compact fusion core.",
        effect: "Unlocks the Fusion Generator ship part.",
      },
      {
        id: "reactor-housing",
        name: "Reactor Housing",
        section: "power",
        tier: 3,
        lane: 0,
        requires: ["fusion-generator", "high-capacity-bus"],
        scrap: 240,
        parts: { "power-generator": 2, "ship-scaffold": 6, "electric-cable": 6 },
        description: "Adds better bracing and cooling around generator blocks.",
        effect: "Each Power Generator and Fusion Generator produce 1 additional power.",
      },
      {
        id: "quantum-capacitors",
        name: "Quantum Capacitors",
        section: "power",
        tier: 4,
        lane: 0,
        requires: ["reactor-housing"],
        scrap: 330,
        parts: { "power-generator": 2, "electric-cable": 12 },
        description: "Stores short bursts of power for demanding advanced systems.",
        effect: "Each Power Generator and Fusion Generator produce 2 additional power.",
      },
      {
        id: "redundant-breakers",
        name: "Redundant Breakers",
        section: "power",
        tier: 2,
        lane: 2,
        requires: ["high-capacity-bus"],
        scrap: 170,
        parts: { "electric-cable": 8, "ship-scaffold": 4 },
        description: "Adds resettable breakers so overloaded cable paths fail less catastrophically.",
        effect: "Prepares the grid for more efficient advanced logistics and weapons.",
      },
      {
        id: "plasma-regulators",
        name: "Plasma Regulators",
        section: "power",
        tier: 5,
        lane: 0,
        requires: ["quantum-capacitors", "redundant-breakers"],
        scrap: 390,
        parts: { "power-generator": 3, "electric-cable": 12 },
        description: "Stabilizes late-game power flow before it reaches weapon and engine systems.",
        effect: "Each Power Generator and Fusion Generator produce 2 additional power.",
      },
      {
        id: "ammo-routing",
        name: "Ammo Routing",
        section: "logistics",
        tier: 0,
        lane: 0,
        scrap: 55,
        parts: { "conveyor-belt": 3, "electric-cable": 2 },
        description: "Marks cleaner ammunition paths through the ship.",
        effect: "Conveyor belts move ammo 15% faster.",
      },
      {
        id: "cargo-racks",
        name: "Cargo Racks",
        section: "logistics",
        tier: 0,
        lane: 2,
        scrap: 70,
        parts: { "ship-scaffold": 5, "conveyor-belt": 2 },
        description: "Adds dedicated storage racks for recovered parts.",
        effect: "Prepares the ship for better salvage processing.",
      },
      {
        id: "feed-gates",
        name: "Feed Gates",
        section: "logistics",
        tier: 1,
        lane: 0,
        requires: ["ammo-routing"],
        scrap: 120,
        parts: { "ammo-factory": 1, "conveyor-belt": 3 },
        description: "Adds metered doors that keep ammunition moving out of factories.",
        effect: "Ammo factories output ammo 10% faster.",
      },
      {
        id: "salvage-sorting",
        name: "Salvage Sorting",
        section: "logistics",
        tier: 1,
        lane: 2,
        requires: ["cargo-racks"],
        scrap: 125,
        parts: { "ship-scaffold": 6, "electric-cable": 4 },
        description: "Sorts scrap from debris before it reaches storage.",
        effect: "Scrap collected by the player is worth 15% more.",
      },
      {
        id: "rapid-ammo-factory",
        name: "Rapid Ammo Factory",
        section: "logistics",
        tier: 2,
        lane: 0,
        requires: ["feed-gates"],
        unlocks: "rapid-ammo-factory",
        scrap: 220,
        parts: { "ammo-factory": 2, "conveyor-belt": 6 },
        description: "Unlocks a faster ammunition factory.",
        effect: "Unlocks the Rapid Ammo Factory ship part.",
      },
      {
        id: "loader-automation",
        name: "Loader Automation",
        section: "logistics",
        tier: 3,
        lane: 0,
        requires: ["rapid-ammo-factory", "salvage-sorting"],
        scrap: 260,
        parts: { "ammo-factory": 2, "conveyor-belt": 8, "electric-cable": 6 },
        description: "Synchronizes factories, conveyors, and cannon breeches.",
        effect: "Ammo factories and conveyors gain an additional speed boost.",
      },
      {
        id: "depot-grids",
        name: "Depot Grids",
        section: "logistics",
        tier: 2,
        lane: 2,
        requires: ["salvage-sorting"],
        scrap: 185,
        parts: { "ship-scaffold": 8, "conveyor-belt": 4, "electric-cable": 4 },
        description: "Organizes salvage into predictable bins as soon as it reaches the ship.",
        effect: "Scrap collected by the player is worth another 10%.",
      },
      {
        id: "factory-overclock",
        name: "Factory Overclock",
        section: "logistics",
        tier: 4,
        lane: 0,
        requires: ["loader-automation"],
        scrap: 330,
        parts: { "ammo-factory": 3, "power-generator": 1, "electric-cable": 8 },
        description: "Pushes ammo factory machinery beyond its normal cycle speed.",
        effect: "Ammo factories output ammo another 10% faster.",
      },
    ],
    WORLD_WIDTH: 12000,
    WORLD_HEIGHT: 12000,
    WORLD_CENTER_X: 6000,
    WORLD_CENTER_Y: 6000,
    WORLD_RADIUS: 5600,
    WORLD_MIDDLE_RADIUS: 3650,
    WORLD_CORE_RADIUS: 1750,
    WORLD_LOCAL_SPAWN_RADIUS: 2200,
    WORLD_ACTIVE_SIM_RADIUS: 2800,
    WORLD_SPAWN_RETENTION_RADIUS: 3800,
    INITIAL_WORLD_ZOOM: 1,
    WORLD_ZOOM_MIN: 0.24,
    WORLD_ZOOM_MAX: 1.35,
    WORLD_ZOOM_STEP: 0.15,
    BUILD_LOCKOUT_DISTANCE: 500,
    SHIP_WORLD_SCALE: 18,
    COLLECTION_RANGE: 120,
    SALVAGE_COLLECTOR_RANGE: 820,
    SALVAGE_COLLECTOR_INTERVAL: 1.25,
    SHIELD_RADIUS_CELLS: 3.25,
    SHIELD_REGEN_RATE: 4,
    SHIELD_PROJECTILE_DAMAGE_RATIO: 0.65,
    ENGINE_FORCE: 48,
    TORQUE_SCALE: 0.000065,
    LINEAR_DAMPING: 0.958,
    ANGULAR_DAMPING: 0.91,
    MAX_WORLD_STEP: 0.05,
    CANNON_AMMO_CAPACITY: 5,
    CANNON_STARTING_AMMO: 0,
    CANNON_PROJECTILE_SPEED: 820,
    WORLD_PART_SPAWN_INTERVAL: 18,
    WORLD_ENEMY_SPAWN_INTERVAL: 70,
    WORLD_TRADER_SPAWN_INTERVAL: 115,
    WORLD_MAX_LOOSE_PIECES: 110,
    WORLD_MAX_ENEMIES: 9,
    WORLD_MAX_TRADERS: 4,
    TRADER_SHIP_COUNT: 2,
    TRADER_TRADE_RADIUS: 420,
    TRADER_STOCK_SLOT_COUNT: 5,
    TRADER_REFRESH_COST: 55,
    TRADER_ARTIFACT_CHANCE: 0.025,
    ENEMY_SCRAP_DROP_MIN: 55,
    ENEMY_SCRAP_DROP_MAX: 120,
    WEAPON_TILE_IDS: ["laser", "beam-laser", "pulse-laser", "cannon", "long-range-cannon", "railgun"],
    CANNON_TILE_IDS: ["cannon", "long-range-cannon", "railgun"],
    CONVEYOR_TILE_IDS: ["conveyor-belt", "splitter-conveyor"],
    ENGINE_TILE_IDS: ["engine", "overdrive-engine", "quantum-thruster"],
    POWER_GENERATOR_TILE_IDS: ["power-generator", "fusion-generator"],
    POWER_OUTPUT_BY_TILE: {
      "power-generator": 8,
      "fusion-generator": 16,
    },
    POWER_REQUIREMENT_BY_TILE: {
      engine: 2,
      "overdrive-engine": 3,
      "quantum-thruster": 4,
      laser: 3,
      "shield-block": 4,
      "beam-laser": 5,
      "pulse-laser": 4,
      cannon: 2,
      "long-range-cannon": 3,
      railgun: 6,
      "ammo-factory": 3,
      "repair-bot-block": 4,
      "salvage-collector": 3,
      "rapid-ammo-factory": 5,
      "conveyor-belt": 1,
      "splitter-conveyor": 1,
    },
    AMMO_FACTORY_TILE_IDS: ["ammo-factory", "rapid-ammo-factory"],
    AMMO_FACTORY_INTERVAL_BY_TILE: {
      "ammo-factory": 1.1,
      "rapid-ammo-factory": 0.55,
    },
    ENGINE_FORCE_BY_TILE: {
      engine: 48,
      "overdrive-engine": 74,
      "quantum-thruster": 98,
    },
    WEAPON_RANGES: {
      laser: 850,
      "beam-laser": 1180,
      "pulse-laser": 760,
      cannon: 900,
      "long-range-cannon": 1600,
      railgun: 2200,
    },
    WEAPON_COOLDOWNS: {
      laser: 0.45,
      "beam-laser": 0.68,
      "pulse-laser": 0.18,
      cannon: 1.15,
      "long-range-cannon": 1.55,
      railgun: 2.35,
    },
    WEAPON_DAMAGE: {
      laser: 22,
      "beam-laser": 35,
      "pulse-laser": 14,
      cannon: 75,
      "long-range-cannon": 95,
      railgun: 140,
    },
    TILE_MAX_HP: {
      core: 150,
      "ship-scaffold": 60,
      "power-generator": 80,
      "fusion-generator": 105,
      engine: 75,
      "overdrive-engine": 90,
      "quantum-thruster": 100,
      laser: 60,
      "shield-block": 90,
      "beam-laser": 70,
      "pulse-laser": 55,
      cannon: 90,
      "long-range-cannon": 105,
      railgun: 120,
      "ammo-factory": 70,
      "repair-bot-block": 80,
      "salvage-collector": 75,
      "rapid-ammo-factory": 75,
      "conveyor-belt": 50,
      "splitter-conveyor": 55,
      "electric-cable": 35,
    },
    CONVEYOR_AMMO_INTERVAL: 0.35,
    CONVEYOR_AMMO_CAPACITY: 3,
    PART_HIT_RADIUS: 12,
    PIECE_HIT_RADIUS: 12,
    PROJECTILE_HIT_RADIUS: 9,
  };
})(window.SpaceCore = window.SpaceCore || {});
