(function (spaceCore) {
  "use strict";

  function getDom() {
    return {
      tutorialView: document.querySelector("#tutorial-view"),
      tutorialTitle: document.querySelector("#tutorial-title"),
      tutorialCopy: document.querySelector("#tutorial-copy"),
      tutorialPoints: document.querySelector("#tutorial-points"),
      tutorialVisual: document.querySelector("#tutorial-visual"),
      tutorialProgress: document.querySelector("#tutorial-progress"),
      tutorialBackButton: document.querySelector("#tutorial-back-button"),
      tutorialNextButton: document.querySelector("#tutorial-next-button"),
      skipTutorialButton: document.querySelector("#skip-tutorial-button"),
      mainMenuView: document.querySelector("#main-menu-view"),
      mainMenuStatus: document.querySelector("#main-menu-status"),
      startSinglePlayerButton: document.querySelector("#start-single-player-button"),
      joinPublicServerButton: document.querySelector("#join-public-server-button"),
      joinPrivateServerButton: document.querySelector("#join-private-server-button"),
      privateRoomPanel: document.querySelector("#private-room-panel"),
      privateRoomCodeInput: document.querySelector("#private-room-code-input"),
      joinPrivateRoomButton: document.querySelector("#join-private-room-button"),
      startNewServerButton: document.querySelector("#start-new-server-button"),
      boardElement: document.querySelector("#board"),
      paletteElement: document.querySelector("#tile-palette"),
      statusElement: document.querySelector("#status-bar"),
      rotateButton: document.querySelector("#rotate-button"),
      eraseButton: document.querySelector("#erase-button"),
      clearButton: document.querySelector("#clear-button"),
      researchButton: document.querySelector("#research-button"),
      saveButton: document.querySelector("#save-button"),
      doneButton: document.querySelector("#done-button"),
      tabs: [...document.querySelectorAll(".tab")],
      selectedPreview: document.querySelector("#selected-preview"),
      selectedLayer: document.querySelector("#selected-layer"),
      selectedName: document.querySelector("#selected-name"),
      selectedCost: document.querySelector("#selected-cost"),
      selectedPlacement: document.querySelector("#selected-placement"),
      selectedOutput: document.querySelector("#selected-output"),
      techTreeOverlay: document.querySelector("#tech-tree-overlay"),
      techTreeTabs: document.querySelector("#tech-tree-tabs"),
      techTreeGrid: document.querySelector("#tech-tree-grid"),
      techTreeScrapValue: document.querySelector("#tech-tree-scrap-value"),
      closeTechTreeButton: document.querySelector("#close-tech-tree-button"),
      scrapValue: document.querySelector("#scrap-value"),
      powerValue: document.querySelector("#power-value"),
      massValue: document.querySelector("#mass-value"),
      scaffoldCount: document.querySelector("#scaffold-count"),
      generatorCount: document.querySelector("#generator-count"),
      poweredCount: document.querySelector("#powered-count"),
      weaponCount: document.querySelector("#weapon-count"),
      constructionView: document.querySelector("#construction-view"),
      worldView: document.querySelector("#world-view"),
      worldMap: document.querySelector("#world-map"),
      worldStatus: document.querySelector("#world-status"),
      worldScrapValue: document.querySelector("#world-scrap-value"),
      worldCargoValue: document.querySelector("#world-cargo-value"),
      worldRangeValue: document.querySelector("#world-range-value"),
      worldSpeedValue: document.querySelector("#world-speed-value"),
      worldInventoryList: document.querySelector("#world-inventory-list"),
      buildButton: document.querySelector("#build-button"),
      tradeButton: document.querySelector("#trade-button"),
      tradeOverlay: document.querySelector("#trade-overlay"),
      tradeTitle: document.querySelector("#trade-title"),
      tradeSubtitle: document.querySelector("#trade-subtitle"),
      tradeScrapValue: document.querySelector("#trade-scrap-value"),
      tradeRefreshButton: document.querySelector("#trade-refresh-button"),
      tradeStockGrid: document.querySelector("#trade-stock-grid"),
      tradeCargoList: document.querySelector("#trade-cargo-list"),
      closeTradeButton: document.querySelector("#close-trade-button"),
      zoomOutButton: document.querySelector("#zoom-out-button"),
      zoomInButton: document.querySelector("#zoom-in-button"),
      selectedEnginesCount: document.querySelector("#selected-engines-count"),
      activeEnginesCount: document.querySelector("#active-engines-count"),
      selectedWeaponsCount: document.querySelector("#selected-weapons-count"),
      enemyCoreStatus: document.querySelector("#enemy-core-status"),
      engineOnButton: document.querySelector("#engine-on-button"),
      engineOffButton: document.querySelector("#engine-off-button"),
      clearSelectionButton: document.querySelector("#clear-selection-button"),
      multiplayerStatus: document.querySelector("#multiplayer-status"),
      multiplayerCount: document.querySelector("#multiplayer-count"),
      shareUrl: document.querySelector("#share-url"),
      hostButton: document.querySelector("#host-button"),
      joinButton: document.querySelector("#join-button"),
      leaveButton: document.querySelector("#leave-button"),
    };
  }

  spaceCore.dom = {
    getDom,
  };
})(window.SpaceCore = window.SpaceCore || {});
