(function (spaceCore) {
  "use strict";

  const TILES = [
    {
      id: "core",
      name: "Core",
      layer: "base",
      cost: 0,
      locked: true,
      placement: "Central ship block.",
      output: "Lose condition if destroyed.",
    },
    {
      id: "ship-scaffold",
      name: "Ship Scaffold",
      layer: "base",
      cost: 5,
      placement: "Connects to core or scaffold.",
      output: "Supports blocks.",
    },
    {
      id: "power-generator",
      name: "Power Generator",
      layer: "block",
      cost: 30,
      placement: "Sits on scaffold.",
      output: "Generates 8 power.",
    },
    {
      id: "fusion-generator",
      name: "Fusion Generator",
      layer: "block",
      cost: 110,
      researchId: "fusion-generator",
      placement: "Sits on scaffold after research.",
      output: "Generates 16 power.",
    },
    {
      id: "engine",
      name: "Engine",
      layer: "block",
      cost: 20,
      rotatable: true,
      placement: "Sits on scaffold.",
      output: "Uses 2 power to add thrust.",
    },
    {
      id: "overdrive-engine",
      name: "Overdrive Engine",
      layer: "block",
      cost: 65,
      rotatable: true,
      researchId: "overdrive-engine",
      placement: "Sits on scaffold after research.",
      output: "Uses 3 power to add stronger thrust.",
    },
    {
      id: "quantum-thruster",
      name: "Quantum Thruster",
      layer: "block",
      cost: 115,
      rotatable: true,
      researchId: "quantum-thruster",
      placement: "Sits on scaffold after research.",
      output: "Uses 4 power to add extreme thrust.",
    },
    {
      id: "laser",
      name: "Laser",
      layer: "block",
      cost: 35,
      placement: "Sits on scaffold.",
      output: "Uses 3 power to fire.",
    },
    {
      id: "shield-block",
      name: "Shield Block",
      layer: "block",
      cost: 85,
      placement: "Sits on scaffold.",
      output: "Uses 4 power to project a small shield bubble, block enemy projectiles, and regenerate shield HP over time.",
    },
    {
      id: "beam-laser",
      name: "Beam Laser",
      layer: "block",
      cost: 75,
      researchId: "beam-laser",
      placement: "Sits on scaffold after research.",
      output: "Uses 5 power to fire a stronger beam at longer range.",
    },
    {
      id: "pulse-laser",
      name: "Pulse Laser",
      layer: "block",
      cost: 90,
      researchId: "pulse-laser",
      placement: "Sits on scaffold after research.",
      output: "Uses 4 power to fire very rapidly at shorter range.",
    },
    {
      id: "cannon",
      name: "Cannon",
      layer: "block",
      cost: 35,
      placement: "Sits on scaffold.",
      output: "Uses 2 power and ammo to fire.",
    },
    {
      id: "long-range-cannon",
      name: "Long Cannon",
      layer: "block",
      cost: 80,
      researchId: "long-range-cannon",
      placement: "Sits on scaffold after research.",
      output: "Uses 3 power and ammo to fire much farther.",
    },
    {
      id: "railgun",
      name: "Railgun",
      layer: "block",
      cost: 135,
      researchId: "railgun",
      placement: "Sits on scaffold after research.",
      output: "Uses 6 power and ammo to fire an extreme-range slug.",
    },
    {
      id: "ammo-factory",
      name: "Ammo Factory",
      layer: "block",
      cost: 28,
      rotatable: true,
      placement: "Sits on scaffold.",
      output: "Uses 3 power to output ammo forward.",
    },
    {
      id: "repair-bot-block",
      name: "Repair Bot Block",
      layer: "block",
      cost: 90,
      placement: "Sits on scaffold.",
      output: "Uses 4 power to launch repair bots while the ship is still.",
    },
    {
      id: "salvage-collector",
      name: "Salvage Collector",
      layer: "block",
      cost: 95,
      placement: "Sits on scaffold.",
      output: "Uses 3 power to pull in one visible loose part or scrap piece at long range.",
    },
    {
      id: "rapid-ammo-factory",
      name: "Rapid Ammo Factory",
      layer: "block",
      cost: 95,
      rotatable: true,
      researchId: "rapid-ammo-factory",
      placement: "Sits on scaffold after research.",
      output: "Uses 5 power to output ammo forward twice as fast.",
    },
    {
      id: "conveyor-belt",
      name: "Conveyor Belt",
      layer: "block",
      cost: 8,
      rotatable: true,
      placement: "Sits on scaffold.",
      output: "Uses 1 power to move ammo forward.",
    },
    {
      id: "splitter-conveyor",
      name: "Splitter Conveyor",
      layer: "block",
      cost: 16,
      rotatable: true,
      placement: "Sits on scaffold.",
      output: "Uses 1 power to route ammo randomly forward, left, or right.",
    },
    {
      id: "electric-cable",
      name: "Electric Cable",
      layer: "underlay",
      cost: 3,
      placement: "Runs under ship tiles.",
      output: "Carries power instantly.",
    },
  ];

  function findTileById(id) {
    return TILES.find((tile) => tile.id === id);
  }

  spaceCore.tileCatalog = {
    TILES,
    findTileById,
  };
})(window.SpaceCore = window.SpaceCore || {});
